[package]
name = "rusty-llm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
llm-chain = "0.13.0"
llm-chain-openai = "0.13.0"
tokio = { version = "1.35.1", features = ["full"] }
